### ISSUE TITLE
Getting Unknown option

### ISSUE THREAD

**Issue by Aphris-Karu** [fentas/docker-volume-davfs#5]
When I try to deploy a stack I get

"create Test_dav-volume: VolumeDriver.Create: unknown option ["url=http://xxxxx:xxxxx@xgnas.home.mmmmm.com:8080/docker/"]"

The Volume entry in Yaml is
```
volumes:
  dav-volume:
    driver: fentas/davfs
    driver_opts:
      o: url=http://xxxxx:xxxxx@xgnas.home.mmmmm.com:8080/docker/
```

I may have that wrong as I was unable to locate any documentation on it.

**Comment by fentas** [comment]
Ouch sorry this issue went under my radar. 😣
Still having trouble with this?

There is no real documentation besides the readme really. 
Have you tried `url: "http..."`?

**Comment by perguth** [comment]
Options from `docker run` should be passed into `driver_opts` of docker-compose:
```
  webdav-client:
    image: fentas/davfs
    volumes:
      - type: volume
        source: webdav
        target: /tmp/webdav-client

volumes:
  webdav:
    driver_opts:
      o: "url=https://<host>"
      o: "username=<user>"
      o: "password=<password>"
      o: "uid=1000"
      o: "gid=1000"
```
